version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: holora_medical_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holora_medical
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: holora_medical_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  backend:
    build:
      context: ../backend
    container_name: holora_medical_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: holora_medical
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: REMOVED_SECRET
      GOOGLE_CLIENT_ID: 949646551056-us2qk9838n66ubnma5b76ekp0bnh6old.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: REMOVED_SECRET
    depends_on:
      - mysql

  frontend:
    build:
      context: ../frontend
      args:
        VITE_GOOGLE_CLIENT_ID: 949646551056-us2qk9838n66ubnma5b76ekp0bnh6old.apps.googleusercontent.com
    container_name: holora_medical_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: